version: '3.8'
services:
  kafka-zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_CFG_LISTENERS: "CLIENT://:9093,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka:9093,EXTERNAL://localhost:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "kafka-zookeeper:2181"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "CLIENT"
    depends_on:
      - kafka-zookeeper

  akhq:
    image: tchiotludo/akhq
    ports:
      - 8080:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9093"
    depends_on:
      - kafka
